### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by fractional-ray** [azavea/raster-vision-examples#61]
I have quick question.

I am running on the command:
rastervision predict https://s3.amazonaws.com/azavea-research-public-data/raster-vision/examples/model-zoo/vegas-building-seg/predict_package.zip https://s3.amazonaws.com/azavea-research-public-data/raster-vision/examples/model-zoo/vegas-building-seg/1929.tif predictions.tif

But what happens is the predictions.tif is black. There is no semantic segmentation on the image. Do I need to process the image before trying to predict?

**Comment by lewfish** [comment]
I know that when I view GeoTIFFs in Mac OS using the built-in image previewer, they appear all black or are otherwise distorted. So I view GeoTIFFs in QGIS. For label images, this is because the values are all low integers (0-6) which don't show up. This is what the predictions look like in QGIS for the command you ran.

![Screen Shot 2019-06-11 at 11 29 02 AM](https://user-images.githubusercontent.com/1896461/59285589-36649a80-8c3c-11e9-9439-351d01aa45ae.png)
